import "./globals.css";

export const metadata = {
    title: "SymbolRush",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-slate-600">{children}</body>
        </html>
    );
}
